---
language: go
sudo: false
services:
  - docker
go:
  - "1.11"
env:
  - GO111MODULE=on

install: true

script:
  - go test -v
  - docker build .

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
